/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant {

    String name;
    int stars;
    int priceCategory;
    ArrayList<Review> reviewList = new ArrayList<>();

    public Restaurant(String name, int stars, int priceCategory) {
        this.name = name;
        this.stars = stars;
        this.priceCategory = priceCategory;
    }

    public String toString() {
        return String.format("Name: %s Stars: %d Price Category: %d", name, stars, priceCategory);
    }

    public void addReview(Review reviewToAdd) {
        reviewList.add(reviewToAdd);
        updateStarRating();
    }

    public void updateStarRating(){
        int total = 0;
        for (int i = 0; i < reviewList.size(); i++) {
            total += reviewList.get(i).stars;
        }
        stars = total / reviewList.size();
    }
}


