/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void main() {
        App classUnderTest = new App();
        assertNotNull("Hi!", classUnderTest.sayHi());
    }
}
